### ISSUE TITLE
🐛 [bug] - OpenMetadata Keycloak - Roles + Logout

### ISSUE THREAD

**Issue by eformat** [opendatahub-io-contrib/data-mesh-pattern#50]
### 📝 Description
Integration for Keycloak based login was added in https://github.com/opendatahub-io-contrib/data-mesh-pattern/pull/49

Two issues need some more work:

(1) No Backchannel logout mechanism in Openmetadata for KC. The frontchannel configured in the example did not seem to work (ie. session remains in KC post logout)

https://github.com/open-metadata/openmetadata-demo/blob/main/keycloak-sso/config/data-sec.json

likely this needs fixing in OMD itself.

(2) The Team / Roles - seem to be managed in the app - i.e. Admin is set using the env.var AUTHORIZER_ADMIN_PRINCIPALS and the default roles in KC client have no effect:

```
  roles:
    - name: DataConsumer
      composite: false
      clientRole: true
    - name: Admin
      composite: false
      clientRole: true
    - name: DataSteward
      composite: false
      clientRole: true
```

Would be nice if these Roles could be managed in KC instead.
